version: '3.3'
services:
  backend:
    image: dto80/se234-lab11:latest
    ports:
      - "8078:8080"
    volumes:
      - type: bind
        source: "D:/data.xlsx"
        target: /home/ubuntu/data
  frontend:
    image: yu11001/ruth:latest
    ports:
      - "8077:80"
